# Generated by Django 4.1.3 on 2022-11-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_init', models.CharField(max_length=3, verbose_name='class init')),
                ('first_lesson', models.CharField(max_length=15, verbose_name='first lesson')),
                ('second_lesson', models.CharField(max_length=15, verbose_name='second lesson')),
                ('thrid_lesson', models.CharField(max_length=15, verbose_name='thrid lesson')),
                ('fourth_lesson', models.CharField(max_length=15, verbose_name='fourth lesson')),
                ('fifth_lesson', models.CharField(max_length=15, verbose_name='fifth lesson')),
                ('sixth_lesson', models.CharField(max_length=15, verbose_name='sixth lesson')),
                ('seventh_lesson', models.CharField(max_length=15, verbose_name='seventh lesson')),
                ('timetable_date', models.DateField(verbose_name='timetable date')),
                ('short_lesson', models.BooleanField(verbose_name='short lesson')),
                ('short_break', models.BooleanField(verbose_name='short break')),
            ],
        ),
    ]
