# Generated by Django 4.1.3 on 2022-11-19 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3, verbose_name='Класс')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_lesson', models.CharField(blank=True, default='—', max_length=15, null=True, verbose_name='first lesson')),
                ('first_cabinet', models.CharField(blank=True, default='—', max_length=10, null=True, verbose_name='first cabinet')),
                ('second_lesson', models.CharField(blank=True, default='—', max_length=15, null=True, verbose_name='second lesson')),
                ('second_cabinet', models.CharField(blank=True, default='—', max_length=10, null=True, verbose_name='second cabinet')),
                ('third_lesson', models.CharField(blank=True, default='—', max_length=15, null=True, verbose_name='third lesson')),
                ('third_cabinet', models.CharField(blank=True, default='—', max_length=10, null=True, verbose_name='third cabinet')),
                ('fourth_lesson', models.CharField(blank=True, default='—', max_length=15, null=True, verbose_name='fourth lesson')),
                ('fourth_cabinet', models.CharField(blank=True, default='—', max_length=10, null=True, verbose_name='fourth cabinet')),
                ('fifth_lesson', models.CharField(blank=True, default='—', max_length=15, null=True, verbose_name='fifth lesson')),
                ('fifth_cabinet', models.CharField(blank=True, default='—', max_length=10, null=True, verbose_name='fifth cabinet')),
                ('sixth_lesson', models.CharField(blank=True, default='—', max_length=15, null=True, verbose_name='sixth lesson')),
                ('sixth_cabinet', models.CharField(blank=True, default='—', max_length=10, null=True, verbose_name='sixth cabinet')),
                ('seventh_lesson', models.CharField(blank=True, default='—', max_length=15, null=True, verbose_name='seventh lesson')),
                ('seventh_cabinet', models.CharField(blank=True, default='—', max_length=10, null=True, verbose_name='second cabinet')),
                ('timetable_date', models.DateField(verbose_name='timetable date')),
                ('short_lesson', models.BooleanField(verbose_name='short lesson')),
                ('short_break', models.BooleanField(verbose_name='short break')),
                ('class_init', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetables.category', verbose_name='Класс')),
            ],
        ),
    ]
