# Generated by Django 4.1.2 on 2022-11-19 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetable',
            old_name='thrid_cabinet',
            new_name='third_cabinet',
        ),
        migrations.RenameField(
            model_name='timetable',
            old_name='thrid_lesson',
            new_name='third_lesson',
        ),
    ]
