# Generated by Django 4.1.2 on 2022-12-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Класс', 'verbose_name_plural': 'Классы'},
        ),
        migrations.AlterModelOptions(
            name='timetable',
            options={'verbose_name': 'Расписание', 'verbose_name_plural': 'Расписания'},
        ),
        migrations.AlterField(
            model_name='timetable',
            name='fifth_cabinet',
            field=models.CharField(blank=True, default='—', max_length=10, null=True, verbose_name='Пятый кабинет'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='fifth_lesson',
            field=models.CharField(blank=True, default='—', max_length=15, null=True, verbose_name='Пятый урок'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='first_cabinet',
            field=models.CharField(blank=True, default='—', max_length=10, null=True, verbose_name='Первый кабинет'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='first_lesson',
            field=models.CharField(blank=True, default='—', max_length=15, null=True, verbose_name='Первый урок'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='fourth_cabinet',
            field=models.CharField(blank=True, default='—', max_length=10, null=True, verbose_name='Четвёртый кабинет'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='fourth_lesson',
            field=models.CharField(blank=True, default='—', max_length=15, null=True, verbose_name='Четвёртый урок'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='second_cabinet',
            field=models.CharField(blank=True, default='—', max_length=10, null=True, verbose_name='Второй кабинет'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='second_lesson',
            field=models.CharField(blank=True, default='—', max_length=15, null=True, verbose_name='Второй урок'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='seventh_cabinet',
            field=models.CharField(blank=True, default='—', max_length=10, null=True, verbose_name='Седьмой кабинет'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='seventh_lesson',
            field=models.CharField(blank=True, default='—', max_length=15, null=True, verbose_name='Седьмой урок'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='short_break',
            field=models.BooleanField(verbose_name='Короткие перемены'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='short_lesson',
            field=models.BooleanField(verbose_name='Короткие уроки'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='sixth_cabinet',
            field=models.CharField(blank=True, default='—', max_length=10, null=True, verbose_name='Шестой кабинет'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='sixth_lesson',
            field=models.CharField(blank=True, default='—', max_length=15, null=True, verbose_name='Шестой урок'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='third_cabinet',
            field=models.CharField(blank=True, default='—', max_length=10, null=True, verbose_name='Третий кабинет'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='third_lesson',
            field=models.CharField(blank=True, default='—', max_length=15, null=True, verbose_name='Третий урок'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='timetable_date',
            field=models.DateField(verbose_name='Дата расписания'),
        ),
    ]
