# Generated by Django 4.1.2 on 2022-11-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0002_rename_thrid_cabinet_timetable_third_cabinet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='fifth_cabinet',
            field=models.CharField(blank=True, default=' ', max_length=3, null=True, verbose_name='fifth cabinet'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='fifth_lesson',
            field=models.CharField(blank=True, default=' ', max_length=15, null=True, verbose_name='fifth lesson'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='first_cabinet',
            field=models.CharField(blank=True, default=' ', max_length=3, null=True, verbose_name='first cabinet'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='first_lesson',
            field=models.CharField(blank=True, default=' ', max_length=15, null=True, verbose_name='first lesson'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='fourth_cabinet',
            field=models.CharField(blank=True, default=' ', max_length=3, null=True, verbose_name='fourth cabinet'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='fourth_lesson',
            field=models.CharField(blank=True, default=' ', max_length=15, null=True, verbose_name='fourth lesson'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='second_cabinet',
            field=models.CharField(blank=True, default=' ', max_length=3, null=True, verbose_name='second cabinet'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='second_lesson',
            field=models.CharField(blank=True, default=' ', max_length=15, null=True, verbose_name='second lesson'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='seventh_cabinet',
            field=models.CharField(blank=True, default=' ', max_length=3, null=True, verbose_name='second cabinet'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='seventh_lesson',
            field=models.CharField(blank=True, default=' ', max_length=15, null=True, verbose_name='seventh lesson'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='sixth_cabinet',
            field=models.CharField(blank=True, default=' ', max_length=3, null=True, verbose_name='sixth cabinet'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='sixth_lesson',
            field=models.CharField(blank=True, default=' ', max_length=15, null=True, verbose_name='sixth lesson'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='third_cabinet',
            field=models.CharField(blank=True, default=' ', max_length=3, null=True, verbose_name='thrid cabinet'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='third_lesson',
            field=models.CharField(blank=True, default=' ', max_length=15, null=True, verbose_name='thrid lesson'),
        ),
    ]
