# Generated by Django 4.1.2 on 2022-11-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0004_alter_timetable_fifth_cabinet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='third_cabinet',
            field=models.CharField(blank=True, default='--', max_length=3, null=True, verbose_name='third cabinet'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='third_lesson',
            field=models.CharField(blank=True, default='--', max_length=15, null=True, verbose_name='third lesson'),
        ),
    ]
